version: '2'
services:
  ns:
    container_name: ns
    build: ./
    # image: legraina/ns
    volumes:
      - ./datasets/:/ns/datasets
      - ./paramfiles/:/ns/paramfiles
      - ./outfiles/:/ns/outfiles
    # command: -i n005w4_0_1-2-3-3  #  -d -s 22-36-96-5
