version: '2'
services:
  ns:
    container_name: ns
    build: ./
    # image: legraina/nurse-scheduler
    volumes:
      - ./datasets/:/ns/datasets
      - ./paramfiles/:/ns/paramfiles
      - ./outfiles/:/ns/outfiles
    command: -i n030w4_0_1-2-3-3
